DROP SCHEMA IF EXISTS hello_schema CASCADE;

CREATE SCHEMA IF NOT EXISTS hello_schema;

CREATE TABLE IF NOT EXISTS hello_schema.users (
    name TEXT PRIMARY KEY,
    count INTEGER DEFAULT(1)
);


DROP SCHEMA IF EXISTS lavka CASCADE;
CREATE SCHEMA IF NOT EXISTS lavka;

CREATE TYPE lavka.courier_type AS ENUM (
    'FOOT',
    'BIKE',
    'AUTO'
);
COMMENT ON TYPE lavka.courier_type IS 'Тип курьера';


CREATE TYPE lavka.timerange AS RANGE (
    subtype = time
);
COMMENT ON TYPE lavka.timerange IS 'Диапазоны времени';


CREATE TABLE IF NOT EXISTS lavka.couriers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    courier_type lavka.courier_type NOT NULL,
    regions integer[],
    working_hours lavka.timerange[] DEFAULT '{}'
);

COMMENT ON COLUMN lavka.couriers.courier_type IS 'Тип курьера';

CREATE TABLE lavka.orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regions integer NOT NULL,
    delivery_hours lavka.timerange[] DEFAULT '{}',
    cost integer,
    weight real,
    complete_time timestamp,
    courier_id integer
);
COMMENT ON TABLE lavka.orders IS 'Заказы';

CREATE TABLE lavka.couriers_assignments (
    courier_id integer NOT NULL,
    time_start time,
    orders integer[]
);
COMMENT ON TABLE lavka.couriers_assignments IS 'Распределенные заказы по курьерам';
